name: update-site

on: 

  push:

    branches:
      - master

  pull_request:

    branches:
      - master

jobs:

  Deploy Site:

    runs-on: ubuntu-latest

    steps:

      - name: Install SSH Key

        uses: shimataro/ssh-key-action@v2.3.0
        with:
          - key: ${{ secrets.SSH_KEY }}
          - known_hosts: "placeholder"

      - run: ssh-keyscan melbourneplace.net >> ~/.ssh/known_hosts
      - run: echo "Hello, World!" > test.txt
      - run: scp -i ~/.ssh/key test.txt pi@melbourneplace.net:~/test.txt
