name: Deploy Site

on: 

  push:

    branches:
      - master

  pull_request:

    branches:
      - master

jobs:

  deploy-site:

    runs-on: ubuntu-latest

    steps:

      - name: Install SSH Key

        uses: shimataro/ssh-key-action@v2.3.0
        with:
          key: ${{ secrets.SSH_KEY }}
          name: mp_key
          known_hosts: "placeholder host since IP is dynamic"
          config: |
            Host mp
              HostName melbourneplace.net
              User pi
              IdentityFile ~/.ssh/mp_key

      - name: Update `known_hosts`
        run: ssh-keyscan -H melbourneplace.net >> ~/.ssh/known_hosts

      - name: Stop the current process
        run: ssh mp "npm kill --prefix melbourne-place"

      - name: Checkout the current code
        uses: actions/checkout@v2

      - name: Upload to server
        run: rsync --delete --delete-excluded -avz ./web mp:/melbourne-place

      - name: Restart the process
        run: ssh mp "npm deploy --prefix melbourne-place"
