name: update-site

on: 

  push:

    branches:
      - master

  pull_request:

    branches:
      - master

jobs:

  deploy-site:

    runs-on: ubuntu-latest

    steps:
      
      - run: ls -la ~
      - run: ssh-keyscan -H melbourneplace.net  >> ~/.ssh/known_hosts
      - run: echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
      - run: echo "Hello, World!" > test.txt
      - run: scp test.txt pi@melbourneplace.net:~/test.txt


