name: Deploy Site

on: 

  push:

    branches:
      - master

  pull_request:

    branches:
      - master

jobs:

  deploy-site:

    runs-on: ubuntu-latest

    steps:

      - name: Install SSH Key

        uses: shimataro/ssh-key-action@v2.3.0
        with:
          key: ${{ secrets.SSH_KEY }}
          name: mp_key
          known_hosts: "placeholder host since IP is dynamic"
          config: |
            Host mp
              HostName melbourneplace.net
              User pi
              IdentityFile ~/.ssh/mp_key

      - name: Update `known_hosts`
        run: ssh-keyscan -H melbourneplace.net >> ~/.ssh/known_hosts

      - name: SSH to server
        run: ssh melbourneplace.net -l pi

      - name: Move to correct directory
        run: cd melbourne-place

      - name: Stop the current process
        run: pm2 stop melbournePlace

      - name: Checkout the current code
        uses: actions/checkout@v2

      - name: Restart the process
        run: pm2 start web/src/server.js --name melbournePlace
