name: update-site

on: 

  push:

    branches:
      - master

  pull_request:

    branches:
      - master

jobs:

  Deploy Site:

    runs-on: ubuntu-latest

    steps:

      - name: Install SSH Key

        uses: shimataro/ssh-key-action@v2.3.0
        with:
          - key: ${{ secrets.SSH_KEY }}
          - name: mp_key
          - known_hosts: "placeholder"
          - config: |
              Host mp
                HostName melbourneplace.net
                User pi
                IdentityFiles ~/.ssh/mp_key

      - name: Update `known_hosts`
          run: ssh-keyscan -H melbourneplace.net >> ~/.ssh/known_hosts

      - name: Copy File
          run: echo "Hello, World!" > test.txt
          run: scp -i ~/.ssh/key test.txt pi@melbourneplace.net:~/test.txt
