name: update-site

on: 

  push:

    branches:
      - master

  pull_request:

    branches:
      - master

jobs:

  deploy-site:

    runs-on: ubuntu-latest

    steps:
      
      - run: ls -la
