name: update-site

on: 

  push:

    branches:
      - master

  pull_request:

    branches:
      - master

jobs:

  deploy-site:

    runs-on: ubuntu-latest

    steps:
      
      - run: echo "${{ secrets.SSH_KEY }}" > SSH_KEY
      - run: echo "Hello, World!" > test.txt
      - run: scp StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i SSH_KEY test.txt pi@melbourneplace.net:~/
